##Basics of numpy and arrays


In [11]:
import numpy as np  #importing numpy library
array=np.array([1,2,3,4,5])
print(array)
##lets perfrom operation on the array
array2=array*2
print("After multiplying by Two",array2)
print("After adding 5",array+5)
print("After subtracting 3",array-3)
print("After dividing by 2",array/2)
print(type(array))

[1 2 3 4 5]
After multiplying by Two [ 2  4  6  8 10]
After adding 5 [ 6  7  8  9 10]
After subtracting 3 [-2 -1  0  1  2]
After dividing by 2 [0.5 1.  1.5 2.  2.5]
<class 'numpy.ndarray'>


## 0 dimension

In [13]:
import numpy as np
array=np.array("A")
print(array.ndim) #check dimention by ndim it will print zero


0


#1 dimesnion array

In [16]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) 
print(array)
print(array.ndim) #it will print 2 it is 2 dimension array
print(array.shape)  #2 rows and 3 columns

[[1 2 3]
 [4 5 6]]
2
(2, 3)
