##Basics of numpy and arrays


In [11]:
import numpy as np  #importing numpy library
array=np.array([1,2,3,4,5])
print(array)
##lets perfrom operation on the array
array2=array*2
print("After multiplying by Two",array2)
print("After adding 5",array+5)
print("After subtracting 3",array-3)
print("After dividing by 2",array/2)
print(type(array))

[1 2 3 4 5]
After multiplying by Two [ 2  4  6  8 10]
After adding 5 [ 6  7  8  9 10]
After subtracting 3 [-2 -1  0  1  2]
After dividing by 2 [0.5 1.  1.5 2.  2.5]
<class 'numpy.ndarray'>


## 0 dimension

In [13]:
import numpy as np
array=np.array("A")
print(array.ndim) #check dimention by ndim it will print zero


0


#1 dimesnion array

In [1]:
import numpy as np
array = np.array([1, 2, 3])
print(array)
print(array.ndim) #it will print 2 it is 2 dimension array
print(array.shape)  #2 rows and 3 columns

[1 2 3]
1
(3,)


# 2 dimensional Array

In [3]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.ndim) #it will print 2 it is 2 dimension array
print(array.shape)  #2 rows and 3 columns

2
(2, 3)


# 3 dimensional Array

In [10]:
import numpy as np
array = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]],
                  [[13, 14, 15], [16, 17, 18]]])
print(array.ndim) #it will print 3 it is 3 dimension array
print(array.shape)  #2 rows and 3 columns
print(array[0, 1, 2]) #it will print 6
print(array*2) #it will multiply each element by 2


3
(3, 2, 3)
6
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]]


#lets print a name from an 3d array

In [ ]:
import numpy as np
array=np.array([[["a","b"],["c","d"]],
                [["e","f"],["g","h"]],
                [["i","j"],["k","l"]],
                [["m","n"],["o","p"]],
                [["q","r"],["s","t"]],  
                [["u","v"],["w","x"]],
                [["y","z"],["-","-"]]])
print(array.ndim) #it will print 3 it is 3 dimension array
print(array.shape)  #2 rows and 3 columns
#lets print name fahad
Name=array[1,0,1]+array[0,0,0]+array[1,1,1]+array[0,0,0]+array[0,1,1]
print("My Name is:",Name) 

3
(7, 2, 2)
My Name is: fahad
