Broadcasting in NumPy is a powerful mechanism that allows you to perform arithmetic operations on arrays of different shapes without explicitly creating copies or loops
conditon:
they are exactly the same size OR
One of the dimensions has a size of 1

In [ ]:
import numpy as np 
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

1
(4,)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


lets check with different dimentions

In [8]:
import numpy as np 
array1=np.array([[1,2,3,4],[5,6,7,8]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
print(array1*array2)  #this will give error as it is not satisfy conditon for broadcasting

(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 