#slicing array basics

In [ ]:
import numpy as np
#4x4 array -2d
array =np.array([[1, 2, 3,4], #row 0
                 [5, 6, 7,8],   #row 1
                 [9, 10, 11,12], #row 2
                 [13, 14, 15,16]]) #row 3
print(array[0])  #this will print the first row of the array

#slicing
#array(start:end:step)  #end=exclusive you can give from 1->0 rowe
print("1st row of the array",array[0:1])   
print("1st and 3rd row of array",array[0:4:2]) 
print("First two rows of array",array[:2]) 
print("Reverse Array",array[::-1])  
print("2nd column of Array:",array[:,1])  
print("1st and 3rd column of array:\n",array[:,::2])  
print("1st two rows and columns of array:\n",array[0:2,0:2])  
print("",array[0:2,0:2]) 

[1 2 3 4]
1st row of the array [[1 2 3 4]]
1st and 3rd row of array [[ 1  2  3  4]
 [ 9 10 11 12]]
First two rows of array [[1 2 3 4]
 [5 6 7 8]]
Reverse Array [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
2nd column of Array: [ 2  6 10 14]
1st and 3rd column of array:
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
1st two rows and columns of array:
 [[1 2]
 [5 6]]
[[1 2]
 [5 6]]
